on:
  pull_request:
      branches:
        - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Codethreat Github Actions
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
      - name: Hello CodeThreat
        id: hello
        uses: thyldrm/jsexampleact@v101
        env:
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
           USERNAME: ${{ secrets.USERNAME }}
           PASSWORD: ${{ secrets.PASSWORD }}
      - name: Get the output time
        run: echo "The time was ${{ secrets.ACCESS_TOKEN }}"
